Correct websub signifiers
Interactions-HSG/yggdrasil pull request #55
Opened 2024-08-30 06:45 UTC by KaiTries

This should solve issue #52 . 

The signifiers are now correctly located in the entity and the topic is now also correctly stated.

2024-08-30 10:04 UTC, danaivach requested changes

2024-08-30 10:04 UTC, danaivach commented on yggdrasil-utils/src/main/java/org/hyperagents/yggdrasil/utils/impl/RepresentationFactoryHMASImpl.java
> -      .setIRIAsString("http://example.org/artifact-rdf")
Consider replacing "http://example.org/artifact-rdf" with an IRI that uses the `baseUri`, e.g., `baseUri + "#artifact-rdf"`.

2024-08-30 10:06 UTC, danaivach commented
@KaiTries, all looks good regarding issue https://github.com/Interactions-HSG/yggdrasil/issues/52.

If additional changes are applied, e.g., regarding the config, please provide a brief overview here before merging. Thanks!

2024-08-30 11:07 UTC, danaivach commented on README.md
> +in a workspace (needs to be a workspace that has an underlying cartago workspace). Correctly specified artifacts can then be used to remotely
cartago -> CArtAgO

2024-08-30 11:08 UTC, danaivach commented on README.md
> +If the environment is disabled, we do not use Cartago and therefore provide less functionality. This also means
cartago -> CArtAgO

2024-08-30 11:08 UTC, danaivach commented on README.md
> +If you do it this way NO underlying cartago workspace will be created!
cartago -> CArtAgO

2024-08-30 11:08 UTC, danaivach commented on README.md
> +The following configurations will all create an underlying cartago workspace instance.
cartago -> CArtAgO

2024-08-30 11:09 UTC, danaivach commented on README.md
> +Specifying an agent in a workspace will automatically create a body artifact in said workspace as well as join the agent in the cartago workspace.
cartago -> CArtAgO

2024-08-30 11:09 UTC, danaivach commented on README.md
> +Specifying an agent in a workspace will automatically create a body artifact in said workspace as well as join the agent in the cartago workspace.
etc.

2024-08-30 11:40 UTC, KaiTries commented
implemented the comments by @danaivach . 

Since this branch built untop of my merge branch, there are some additional features that are part of this pull request:

- Complete reformatting such that the entire code base once again conforms to the checkstyle guidelines, refactored the code acording to pmd and checkBugs. 
- Renamed RdfStoreVerticle function "UpdateEntity" -> "ReplaceEntity" so that it is closer to its actual functionality
- Added new RdfStoreVerticle function "UpdateEntity" that actually updates a representation and does not replace already existing data. 
    - HttpHandler now utilizes this new function and when creating an entity through turtle, first a base representation is created and then the user sent representation is updated on top of that entity.
- Base Refactor of the configuration files for issue #56 
    - This came with some refactoring of the initialization code and the environment parser but does not cause any change in functionality
    - Added support for the "metadata" tag so that cartago entities can be initialized with additional metadata.
- Updated README with an overview of the config file structure

2024-08-30 11:54 UTC, KaiTries commented
still TODO:

- update test ttl files again

2024-09-02 07:09 UTC, KaiTries commented
Updated all test files and reformatted changes to be checkstyle conforming. 

Should be ready to merge

2024-09-09 08:50 UTC, danaivach approved these changes

2024-09-12 13:32 UTC, andreiciortea approved these changes
Thanks @KaiTries!

2024-09-12 13:32 UTC, merged