Improved Configurations, WebSub, explicit joining, http responses
Interactions-HSG/yggdrasil pull request #63
Opened 2024-10-17 07:34 UTC by KaiTries

Hello all, i have once again bundled up all that I have worked on in the past weeks.

Changelog:
- Improved Configurations - for detailed discussion on the changes see issue #56 
    - The new configuration files allow for more freedom and fine-grained selection of the wanted environment. It expands the current configuration and mostly builds on top of it.
    - The new possible specifications are:
        - Agents:
            - Agents can now be defined at the top level of the configuration, independent of the environment. Each Agent can have a list of bodies, that can be independently assigned to workspaces with possible different representations.
        - Workspaces:
            - Workspaces no longer house agents, but still have a list of agents, where you can specify which agent is expected to be joined in the workspace (this can also be specified in the agent itself).
        - Artifacts:
            -  Artifacts are mostly unchanged, but they have an additional optional field for "createdBy" that can specify which specific agent should instantiate the artifact. This is to future proof the configurations once permissions are added. If no agent is specified they are created by a temporary construction agent that is removed from the system once the setup finishes.
        - Metadata
            - All the above can also optionally specify metadata, this should specify a .ttl file. The data in the file will be added to the rdf representation.
    - **Breaking changes:**  
        - Agents are now parsed at a different level, so they will no longer be recognized in old configurations. 
    - In the /conf folder there are example configurations

- Explicit Joining - see issue #57 
    - To be more alligned with the JaCaMo metamodel and to fix some memory leaks, certain operations now **require** the agent to explicitly join the workspace before they are able to do them.
    - **focus, instantiateArtifact and doAction** all now require the agent to be present in the workspace.
    - This only affects cartago artifacts. 
    - doAction means any endpoint specified by a digital artifact hosted on yggdrasil that specifies a cartago operation.
    - If an agent tries to do any of the operations but is not joined a 405 Method not allowed is returned

- WebSub - see issue #58 
    - To be more in line with the intended use of WebSub according to the specifications we refactored it a bit. Most is unchanged, the main changes are how we subscribe to workspaces and artifacts.
    - /workspaces/ and /workspaces/:wkspid/artifacts/ are now resources as well and reachable by GET requests. The return a list of contained entities. The list is a RDF model that specifies the parent resource and the child resources.
    - Subscribing to workspaces - /workspaces/
        - The /workspaces/ endpoint now allows agents to subscribe to top level workspace creation and deletion. Upon change a subscribed agent will receive the updated list of contained workspaces. The platform now exposes a new signifier that points to this endpoint and acts as entry to the websub protocol. To subscribe to subWorkspaces, the endpoint can be subscribed to with path params.
        - /workspaces?parent=parentWorkspaceName allows an agent to do the same thing as above, but for any specific workspace. Each workspace also points to their specific paremeterized endpoint with a new signifier
    - Subscribing to artifacts - /workspaces/:wkspid/artifacts/
        - This endpoint now does the exact same thing as the /workspaces/ one just for artifacts. It can also be reached through GET, returns a list of contained artifacts and has the same functionality with WebSub. The workspaces also have a new signifier specifying this resource.

- Http Responses - e.g. issue #62 
    - Most non happy paths currently return a 500. I did some refactoring to extend the error handling and return some more fitting http responses.

This should be the most important changes. Tests have been updated and new tests have been added.

2024-10-29 11:23 UTC, danaivach requested changes
Regarding WebSub: when I run `java -jar build/libs/yggdrasil-0.0.0-SNAPSHOT-all.jar -conf conf/localhost_memory_config_hmas.json`, and `GET` `/workspaces/w1/artifacts` the response payload considers some SHACL shapes as `hmas:Artifact`. My guess is that the workspace triples are filtered only based on the object `hmas:Artifact`; if this is the case, it would be useful to also consider the predicate `rdf:type` during filtering.

```rdf
@base <http://172.27.52.55:8080/> .
@prefix hmas: <https://purl.org/hmas/> .

<workspaces/w1/#artifact-shape> <http://www.w3.org/ns/shacl#class> hmas:Artifact .

<workspaces/w1/#artifact-rdf> <http://www.w3.org/ns/shacl#class> hmas:Artifact .

<workspaces/w1/artifacts/body_test_agent/#artifact> a hmas:Artifact .

<workspaces/w1/artifacts/c1/#artifact> a hmas:Artifact .
```

Regarding Focus: the `focus` is advertised in artifact profiles (e.g., with a target `workspaces/w1/artifacts/c1/focus/`), but in reality the action works with workspace endpoints (I had to send a request to`/workspaces/w1/focus/`):
- The action spec should be aligned with the action to be performed, and advertised in the relevant profile.
- The action spec should also have an input spec (e.g, `callbackIri` and `artifactName` if the action is offered by workspaces, or `callbackIri` if the action is offered by artifacts).
- Using `/workspaces/w1/focus` worked, but using `/workspaces/w1/focus/` (with a slash) returned a 405. Is this on purpose? If yes, the action spec should have a target without a slash.

2024-10-30 11:12 UTC, KaiTries commented
Thank for the feedback Danai.
I have fixed the issue regarding the /artifacts/ endpoint.
Also the /focus endpoint should now be correctly advertised in both ontologies. Currently the hmas ontology does not specify the input for the focus operation (TODO)

2024-11-07 22:07 UTC, andreiciortea approved these changes
Many thanks, @KaiTries. I pushed a `gradle.properties` file to set higher connection timeout limits. This should solve the occasional issue with JitPack taking a long time to finish a build. Otherwise, no further comments besides what we've already addressed last week.

2024-11-08 13:45 UTC, danaivach approved these changes

2024-11-08 13:46 UTC, merged